// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_GYM_Genie.DBConection;

#nullable disable

namespace Sistema_GYM_Genie.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20231022033657_Version5")]
    partial class Version5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<int>("AlturaDireccion")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI_Persona")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TelefonoPersona")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Cliente", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Persona");

                    b.Property<int>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<float>("PesoCliente")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Profesor", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Persona");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CBU")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<float>("Sueldo")
                        .HasColumnType("real");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Rol", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Persona");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("TipoRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Rol");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Pago", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Cliente");

                    b.Property<float>("MontoPago")
                        .HasColumnType("real");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Pago");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Reserva", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Cliente");

                    b.Property<DateTime>("DiaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Reserva");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Clase", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Reserva");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Equipamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreClase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoClase")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Clase");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Turno", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Clase");

                    b.Property<DateTime>("DiaTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFinTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicioTurno")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Turno");
                });
#pragma warning restore 612, 618
        }
    }
}
