// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_GYM_Genie.DBConection;

#nullable disable

namespace Sistema_GYM_Genie.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    [Migration("20231106030250_Version1")]
    partial class Version1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("PersonaSequence");

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Clase", b =>
                {
                    b.Property<int>("ClaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaseId"));

                    b.Property<float>("CostoClase")
                        .HasColumnType("real");

                    b.Property<string>("Equipamiento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreClase")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("ProfesorDNI")
                        .HasColumnType("int");

                    b.HasKey("ClaseId");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Inscripcion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteDNI_Persona")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("ClienteDNI_Persona");

                    b.ToTable("Incripciones");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Persona", b =>
                {
                    b.Property<int>("DNI_Persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [PersonaSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("DNI_Persona"));

                    b.Property<string>("ApellidoPersona")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Contrasenia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePersona")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TelefonoPersona")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("DNI_Persona");

                    b.ToTable("Personas", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime>("DiaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraReserva")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<DateTime>("DiaTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFinTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicioTurno")
                        .HasColumnType("datetime2");

                    b.HasKey("TurnoId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Cliente", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Persona");

                    b.Property<int>("AlturaCm")
                        .HasColumnType("int");

                    b.Property<float>("PesoCliente")
                        .HasColumnType("real");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Profesor", b =>
                {
                    b.HasBaseType("Sistema_GYM_Genie.Clases.Persona");

                    b.Property<string>("Alias")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<float>("Sueldo")
                        .HasColumnType("real");

                    b.Property<string>("Titulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("Sistema_GYM_Genie.Clases.Inscripcion", b =>
                {
                    b.HasOne("Sistema_GYM_Genie.Clases.Clase", "Clase")
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_GYM_Genie.Clases.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteDNI_Persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
